### ISSUE TITLE
Segmentation fault when integrating with pyarrow batches

### ISSUE THREAD

**Issue by rodrigolece** [hristo-vrigazov/mmap.ninja#7] opened 2022-08-17 18:12 UTC
I want to create a `RaggedMmap` from a large Parquet file.

PyArrow has a nice functionality for iterating over the file and handling groups of rows with `import pyarrow.parquet as pq; pq.ParquetFile("<FILE_PATH>").iter_batches()`, and I would like to use this with the `RaggedMmap.from_generator()` method.

This works just fine if I select a `batch_size` that is bigger than the number of groups read by PyArrow, but if I select a batch size that is smaller then I'm pretty sure that I get a segmentation fault (I'm running this inside a Jupyter notebook and what I see is that the kernel dies).

As I said the Parquet file is large but the following reproduces the behaviour with synthetic data:

```python
import itertools

import numpy as np
import pyarrow as pa
from mmap_ninja.ragged import RaggedMmap

rng = np.random.default_rng(0)

l1 = pa.array([rng.choice(10, size=s) for s in [2, 4, 3, 1]])
b1 = pa.RecordBatch.from_arrays([l1], names=["test"])

l2 = pa.array([rng.choice(10, size=s) for s in [3, 5, 2]])
b2 = pa.RecordBatch.from_arrays([l2], names=["test"])

batches = itertools.chain(b1, b2)
# batches = map(lambda x: x.to_numpy(zero_copy_only=False), batches)
# batches = list(batches)

MMAP_BATCH_SIZE = 1

mmap = RaggedMmap.from_generator(
    out_dir="/tmp/mmap/",
    sample_generator=batches,
    batch_size=MMAP_BATCH_SIZE,
    verbose=True,
)

print(len(mmap))  # 2

mmap[0]
# memmap([array([8, 6]), array([5, 2, 3, 0]), array([0, 0, 1]), array([8])], dtype=object)

mmap[1] 
# kills the kernel

```

If I set `MMAP_BATCH_SIZE` to be anything larger than 2 the code above works fine. The trouble is that for a large Parquet file this means reading the whole file into memory therefore defeating the purpose of using the iterator in the first place.

I also found that if I uncomment BOTH of the lines that transform the batches first into a map of numpy convertors and then instantiate this as a list, the code works as expected. Commenting either one of the lines leads to either a dead kernel or reading what I assume is a random place of memory like so:

```python
mmap[1]
# memmap(['1cd5fed7-b8cc-44ef-808f-7915af221aca',
#         '7c5adda2-b541-476a-b64a-90cb5caa2ac4',
#         b'kernel.feaec815-ef43-42c0-8197-12eb358c28ab.execute_input'],
#        dtype=object)
```

My environment :

```python
import sys
from pprint import pprint

pprint({"sys":sys.version, "np": np.__version__, "mmap_ninja":mmap_ninja.__version__,  "pyarrow": pa.__version__}})
# {'mmap_ninja': '0.2.4',
#  'np': '1.22.3',
#  'pyarrow': '8.0.0',
#  'sys': '3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC '
#         '10.3.0]'}
```

**Comment by hristo-vrigazov** [comment] 2022-08-17 20:12
Thank you so much for reporting this! I have not used it in this way with pyarrow, I will check and get back to you (may take a few days/weeks)

**Comment by rodrigolece** [comment] 2022-08-18 09:30
No problem and thank you for looking into it :) Were you able to reproduce? Otherwise I might be able to share a parquet file with you if needed.

**Comment by hristo-vrigazov** [comment] 2022-08-30 22:53
Hi again, sorry once again for taking so long to respond. So I think that the problem is that `RecordBatch` are not actual iterators, so `itertools.chain` does not work as one would expect them to. Also, we have wrapped in one additional list, so we need one more iteration to make it flat.

```python
import itertools

import numpy as np
import pyarrow as pa
from mmap_ninja.ragged import RaggedMmap
from typing import List

rng = np.random.default_rng(0)

l1 = pa.array([rng.choice(10, size=s) for s in [2, 4, 3, 1]])
b1 = pa.RecordBatch.from_arrays([l1], names=["test"])

l2 = pa.array([rng.choice(10, size=s) for s in [3, 5, 2]])
b2 = pa.RecordBatch.from_arrays([l2], names=["test"])

def generate_from_record_batches(record_batches: List[pa.RecordBatch]):
    for record_batch in record_batches:
        for arr in record_batch:
            for sample in arr:
                yield sample.as_py()

batches = generate_from_record_batches([b1, b2])

MMAP_BATCH_SIZE = 1

mmap = RaggedMmap.from_generator(
    out_dir="/tmp/mmap/",
    sample_generator=batches,
    batch_size=MMAP_BATCH_SIZE,
    verbose=True,
)

print(len(mmap))  # 7

mmap[0] # [8, 6]
``` 

Let me know if it answers your question. I think I will add a clearer assert that would check for cases like this, in which individual samples are not numpy arrays. This would have given you a clearer error and maybe steered it into the right direction.

**Comment by hristo-vrigazov** [comment] 2022-09-15 13:45
Closing this, feel free to ask more questions or report some other bug/inconvenience you encounter :)

**Closed by hristo-vrigazov** 2022-09-15 13:45 UTC
